# .scrutinizer.yml
checks:
  php:
    code_rating: true
    duplication: true

build_failure_conditions:
  - 'elements.rating(<= B).exists'               # No classes/methods with a rating of D or worse
  - 'elements.rating(<= B).new.exists'           # No new classes/methods with a rating of D or worse
  - 'patches.label("Doc Comments").exists'       # No doc comments patches allowed
  - 'patches.label("Spacing").new.count > 1'     # More than 1 new spacing patch
  - 'issues.label("coding-style").exists'        # No coding style issues allowed
  - 'issues.label("coding-style").new.exists'    # No new coding style issues allowed
  - 'issues.severity(>= MINOR).new.exists'       # No new issues of minor or higher severity
  - 'issues.severity(>= MINOR).exists'           # No issues of minor or higher severity
  - 'project.metric("scrutinizer.quality", < 9.9)' # Code Quality Rating drops below 6

build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          -
            command: php-scrutinizer-run
          - phpcs-run --standard=phpcs.xml